apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-bus-depl
spec:
  replicas: 1 # number of pods to create running a specific image
  selector:
    matchLabels:
      app: events-bus
  template:
    metadata:
      labels:
        app: events-bus
    spec:
      containers:
        - name: events-bus
          image: katzg/events-bus # :latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: events-bus-srv
spec:
  # type: ClusterIP # optional: default behavior
  selector:
    app: events-bus
  ports:
    - name: events-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
